apiVersion: v1
kind: Service
metadata:
  name: hello7-service
  namespace: hello7
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30006
  selector:
    app: hello7-deployment
